.TH Xchange-CLI "1" "June 2016" "Xchange-cli 0.12"
.SH NAME
Xchange-cli \- a remote procedure call client for Xchange Core. 
.SH SYNOPSIS
Xchange-cli [options] <command> [params] \- Send command to Xchange Core. 
.TP
Xchange-cli [options] help \- Asks Xchange Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the Xchange-cli program. Xchange-cli is an RPC client used to send commands to Xchange Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBXchanged\fP, \fBXchange.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
